config/routes.rb
SandiMVP::Application.routes.draw do
  get "domov/galerija"
  get 'auth/facebook/callback', to: 'session#create'
  get 'auth/failure', to: redirect('/')
  get 'singout', to: 'session#destroy', as: 'signout'

  resources :eventis
  resources :blogs

  get 'domov/bio', as: 'bio'
  get 'domov/galerija', as: 'galerija'

    root 'domov#index', as: 'domov'

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base

end

app/models/eventi.rb
class Eventi < ActiveRecord::Base

	scope :upcoming, ->{where('zacetek > ?', DateTime.now)}
	scope :past,     ->{where('zacetek < ?', DateTime.now)}
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
		where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.name = auth.info.name
			user.oauth_token = auth.credentials.token
			user.oauth_expires_at = Time.at(auth.credentials.expires_at)
			user.save!
		end
	end

	def facebook
		@facebook ||= Koala::Facebook::API.new(oauth_token)
	end

	def sandi_albums
		slike = facebook.get_connection('292534410868883','photos')
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user


  private

  	def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  	end



  end
  

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.order("created_at DESC")
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to domov_path }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.js{redirect_to domov_path}
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:naslov, :opis, :slika)
    end
end

app/controllers/domov_controller.rb
class DomovController < ApplicationController

  def index
  	@blogs = Blog.all.order("created_at DESC").limit(2)
  	@upcoming = Eventi.upcoming.reverse
  	@past = Eventi.past.reverse
  end

  def bio

  end

  def galerija
  	@slike = current_user.sandi_albums
  end  

end

app/controllers/eventi_controller.rb
class EventiController < ApplicationController
  def naslov:string
  end

  def opis:text
  end

  def kraj:string
  end

  def kdaj:integer
  end
end

app/controllers/eventis_controller.rb
class EventisController < ApplicationController
  before_action :set_eventi, only: [:show, :edit, :update, :destroy]

  # GET /eventis
  # GET /eventis.json
  def index
    @eventis = Eventi.all
  end

  # GET /eventis/1
  # GET /eventis/1.json
  def show
  end

  # GET /eventis/new
  def new
    @eventi = Eventi.new
  end

  # GET /eventis/1/edit
  def edit
  end

  # POST /eventis
  # POST /eventis.json
  def create
    @eventi = Eventi.new(eventi_params)

    respond_to do |format|
      if @eventi.save
        format.html { redirect_to @eventi, notice: 'Eventi was successfully created.' }
        format.json { render action: 'show', status: :created, location: @eventi }
      else
        format.html { render action: 'new' }
        format.json { render json: @eventi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventis/1
  # PATCH/PUT /eventis/1.json
  def update
    respond_to do |format|
      if @eventi.update(eventi_params)
        format.html { redirect_to @eventi, notice: 'Eventi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @eventi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventis/1
  # DELETE /eventis/1.json
  def destroy
    @eventi.destroy
    respond_to do |format|
      format.html { redirect_to eventis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eventi
      @eventi = Eventi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eventi_params
      params.require(:eventi).permit(:naslov, :opis, :kraj, :zacetek)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def create
		user = User.from_omniauth(env['omniauth.auth'])
		session[:user_id] = user.id
		redirect_to domov_path
	end

	def destroy
		session[:user_id] = nil
		redirect_to domov_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/domov_helper.rb
module DomovHelper
end

app/helpers/eventi_helper.rb
module EventiHelper
end

app/helpers/eventis_helper.rb
module EventisHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>


  <div class="field">
    <%= f.label :naslov %><br>
    <%= f.text_field :naslov %>
  </div>
  <div class="field">
    <%= f.label :opis %><br>
    <%= f.text_area :opis %>
  </div>
  <div class="field">
    <%= f.label :slika %><br>
    <%= f.text_field :slika %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div class="large-12 columns blogs">
<h1>My way, My style</h1>
<% for blog in @blogs %>
  <div class="blog">
    <%= image_tag(blog.slika) %>
    <h3><%= blog.naslov %></h3>
    <%= sanitize(blog.opis) %> <br />
    <%= blog.created_at.strftime('%I:%M %b %d, %Y')%>
    <%= button_to "Delete", blog,method: :delete %>
  </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<p>
  <strong>Naslov:</strong>
  <%= @blog.naslov %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @blog.opis %>
</p>

<p>
  <strong>Slika:</strong>
  <%= @blog.slika %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', domov_path %>

app/views/domov/bio.html.erb
<div class="bio">
<h1>BIO</h1>
	<div class="row">
		<div class="large-4 small-8 columns">
			<div class="panel">
				<p>Od majhnih nog sem krasil odre, na katerih sem čutil, da sta trema in kontrola mase moj placebo endorfina, beseda moja katarza in oder moje platno svobodnih barv. Hip hop je vse to sprejemal in dovolil, da sem to kar sem in zaradi pozornosti mi ni potrebno prilagajanje, če sem sprejet širše ker sem kar sem. Biti svoboden. Z besedami risati čustva, misli, domišljijo. Biti na odru jaz, tak kot sem.</p>
			</div>
		</div>
		<div class="large-8 small-4 columns bio_first">
			<%= image_tag 'bio_first.png', class: 'bio_first1' %>
			<%= image_tag 'bio_first2.png', class: 'bio_first2' %>
		</div>
	</div>
	<div class="row">	
		<div class="large-3 columns bio_second">
			<%= image_tag 'bio_second.png', class: 'bio_second1' %>
			<%= image_tag 'bio_second2.png', class: 'bio_second2' %>
		</div>				
		<div class="large-9 small-12 columns">
			<div class="panel">
				<p><strong>Prvič mi je bilo 2006.</strong>, na rap koncertu v MCP-ju (SAM100G, 7INK, LADY B). Bila je potrditev. To je to, kar bi rad, to je način, ki bo ustrezal. Svojo poezijo sem počasi pretvarjal v rap besedila, dobil na samozavesti in eksperimentiral. Istega leta sem posnel svoj prvi feat. s  		<strong>100Ass-om</strong>, danes znanim pod imenom <strong>STOTKA</strong> v domačem studiu, <strong>studiu Armagedon</strong>, doma pri MC As-u, v katerem se je formirala prva postava <strong>Armagedon tim</strong>-a. Kot občasen gost studia, sem dobil potrditve in podporo članov, s katerimi sem posnel komad z naslovom <strong>A ga čutš (2007)</strong>. Počasi je stvar postala jasna in moj elan me ob reformaciji skupine je pripeljal do članstva (2008).</p>
			</div>
		</div>
	</div>
	</div>
	<div class="row">
		<div class="large-4 columns">
			<div class="panel">
				<p>V dveh norih letih smo preselili studio v druge prostore (bivša diskoteka Tango), naredili kup materiala, imeli kup nastopov, posneli prvi studijski posnetek (<strong>Radio 94</strong>) in dali skozi marsikaj, a zaradi nesoglasij in različnih interesov in pogledov na rap glasbo se je zasedba skrčila in sčasoma odvrgla sidro nekje okoli bermudskega trikotnika. Z imenom smo še vedno vztrajali in obstali na treh članih, kateri smo počasi tudi odplavali vsak s svojim tokom. Kljub vsemu, je bil to moj prvi timski razvoj, prva pripadnost, prva ekipa. Zame osebno so to nepozabni trenutki, nepozabni ljudje in predvsem nepozabne izkušnje ("...to u srcu nosm, ush devet je notr, ko pridm gor na odr")</p>
			</div>
		</div>
		<div class="large-4 columns">
			<div class="panel">
				<p>2009-2010 sem živel v Ljubljani, kjer sem s trebuhom za kruhom dobil službo in se preselil v stanovanje skupaj z <strong>MC Edotom</strong> in <strong>STOTKO</strong>. 2010 sem sodeloval pri komadu, ki ga je <strong>Markan</strong> posnel za projekt Ostou bom dol za svoje, ki je moj rap dvignil na naslednji nivo. Sodelovanje me je postavilo na svoje mesto in od takrat pišem svoj rap "proper". Velik vpliv mi je bil tudi <strong>MC Edo</strong>, ki mi je odprl pogled na rap čisto v drugačni luči. Človek s katerim sem največkrat nastopal in obiskoval koncerte in katerega sem najdlje poslušal freestylat in se nisem naveličal</p>
			</div>
		</div>
		<div class="large-4 columns">
			<div class="panel">
				<p>Zaradi zdravstvenih težav sem se bil primoran preseliti nazaj v domači kraj. Kar niti ni bilo napak. V letu v ljubljani sem spoznal veliko za življenje pomembnih otenkov vsakdana. Seveda sem se priključil v studio, ki je bil tokrat v uradno najetem prostoru in posnel kar nekaj materiala, ki je večinoma ostal spravljen za nove ideje. Nastopal sem še vedno, z istim tempom, spoznaval artiste in se spoprijateljil z mnogimi</p>
			</div>
			<div class="bio_third">
				<%= image_tag 'bio_third.png'  %>
				<%= image_tag 'bio_third2.png', class: 'bio_third2' %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<div class="panel">
				<p>2010-2012 sem nastopal po različnih koncih slovenije, večinoma z MC Edotom in STOTKO (kot Armagedon tim) in se tokom dogodkov razvil v samostojnega artista in organizatorja dogodkov. <strong>Organiziral</strong> sem  več rap koncertov po Postojnskih lokalih, pomagal pri organizaciji, sodeloval ali pa nastopal pri skoraj vsakem <strong>hip hop dogodku</strong> (od 2010 dalje) v Postojni, z željo po razvoju hip hopa in da prikažem Postojni rap v dobri luči. Začel sem delati na solo projektih in objavil nekaj demo komadov.  2012 sem zasnoval projekt, ki naj bi bil moj prvi zaključen izdelek, tudi v fizični obliki. Spoprijateljil sem se in začel sodelovati tako studijsko kot tudi na odru z <strong>Izičem</strong> - Izidor Čegrlja. Beatmaker in raper iz Cerknice, je s svojim pristopom in pridihom west coast produkcij pustil name vtis, ki sva ga nadgradila v sodelovanje, ki bo v bodoče zaključen v daljšo celoto</p>
			</div>
		</div>
		<div class="large-12 columns">
			<div class="panel">
				<p><strong>Decembra 2012</strong> sem držal svoj prvi <strong>plošček</strong> v roki. Kratek a jedrnat projekt, me je pahnil v smer, kamor sem vedno želel zaiti. <strong>LoOPzILLa</strong> - Denis Trnolšek je beatmaker zaradi katerega je projekt sploh nastal. Z veliko volje, truda in aspekta, je nadgradil svoj beatmaking do levela, ki ga producenti ne dosegajo več. Lotila sva se sodelovanja, ki se je obneslo in obrodilo prvi rap plošček s postojnskega. LoOPzILLa pa je razlog za moj tekstovni in predvsem tehnični <strong>napredek</strong></p>
			</div>
		</div>
	</div>
</div>

app/views/domov/create.js.erb
    $('#myModal').foundation('reveal', 'open', 'http://localhost:3000/blogs/new');

app/views/domov/galerija.html.erb
<div id="galerija">
	<div class="sredina_g">
		<% @slike.each do |album| %>
			<div class="th radius razmak">
				<%= image_tag(album["source"], class: "fb_galerija") %>
			</div>
		<% end %>
	</div>
</div>

app/views/domov/index.html.erb
      <!-- Main Content -->
 
        <div class="row"> 
          <div class="large-8 columns"> 
            <div class="flex-video">
              <iframe id="player" type="text/html" width="100%" height="390"
    src="http://www.youtube.com/embed/RivvdphxvCk?enablejsapi=1&origin="
    frameborder="0"></iframe>
            </div>
          </div>
 
 
          <div class="large-4 small-8 columns vmesni_razmak">
              <iframe id="sc-widget" src="https://w.soundcloud.com/player/?url=http://api.soundcloud.com/sandi-mvp" width="100%" height="430" scrolling="no" frameborder="no"></iframe>    
          </div>
 
              <div class="large-6 small-12 columns">
                <div class="panel eventi radius event_upcoming">
                  <div class="sredina_eventi">
                    <h4>Prihajajoci Eventi:</h4>
                  </div>
                  <div class="upcoming_slide">
                    <div class="content_eventi">
                      <% for upcoming in @upcoming %>
                      <div class="fn-basic">
                        <div class="list_events">
                          <h5><%=upcoming.naslov %></h5>
                          <p><strong>Opis:</strong> <%=upcoming.opis %></p>
                          <p><strong>Kraj:</strong> <%= upcoming.kraj %></p>
                          <p><strong>Zacetek:</strong> <%= upcoming.zacetek.strftime('%I:%M %b %d, %Y') %> </p>
                        </div>
                      </div>
                      <% end %>
                    </div>  
                  </div>  
                </div>
              </div>
 
              <div class="large-6 small-12 columns vmesni_razmak">
                <div class="panel eventi radius ">
                  <div class="sredina_eventi">
                    <h4>Pretekli Eventi:</h4>
                  </div>
                  <div class="past_slide">
                    <div class="content_eventi">
                      <% for past in @past %>
                        <div class="list_events">
                          <h6><%=past.naslov %></h6>
                          <p><strong>Opis:</strong> <%= past.opis %></p>
                          <p><strong>Kraj:</strong> <%= past.kraj %></p>
                          <p><strong>Zacetek:</strong> <%= past.zacetek.strftime('%I:%M %b %d, %Y') %> </p>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
        </div>
 

 
      <!-- End Main Content -->
 
 
      <!-- Vmesnik -->
 
        <div class="vmesnik">
        </div>
 
      <!-- End Vmesnik -->
 
 
      <!-- Blog -->
 
       <div class="row blog_domov">
          <img src="assets/body_blog.png" alt="">
                <% for blog in @blogs %>              
                  <div class="large-12 small-10">
                    <div class="panel_for_blog">
                     <h3><%= blog.naslov %></h3>
                     <p><%= truncate(strip_tags(blog.opis), length: 75) %></p>
                     <%= link_to "Preberi vec", blog %>
                     <p class="datum"><%= blog.created_at.strftime('%I:%M %b %d, %Y') %></p>
                    </div>
                  </div>
                 <% end %>
 
        </div>
 
      <!-- End Blog -->

      <div id="test">
        <%= image_tag('https://www.facebook.com/media/set/?set=a.103402036340877.7731.100000132441096&type=1&l=a9cd17595f/') %>
      </div>

app/views/eventi/kdaj:integer.html.erb
<h1>Eventi#kdaj:integer</h1>
<p>Find me in app/views/eventi/kdaj:integer.html.erb</p>

app/views/eventi/kraj:string.html.erb
<h1>Eventi#kraj:string</h1>
<p>Find me in app/views/eventi/kraj:string.html.erb</p>

app/views/eventi/naslov:string.html.erb
<h1>Eventi#naslov:string</h1>
<p>Find me in app/views/eventi/naslov:string.html.erb</p>

app/views/eventi/opis:text.html.erb
<h1>Eventi#opis:text</h1>
<p>Find me in app/views/eventi/opis:text.html.erb</p>

app/views/eventis/_form.html.erb
<%= form_for(@eventi) do |f| %>
  <% if @eventi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eventi.errors.count, "error") %> prohibited this eventi from being saved:</h2>

      <ul>
      <% @eventi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :naslov %><br>
    <%= f.text_field :naslov %>
  </div>
  <div class="field">
    <%= f.label :opis %><br>
    <%= f.text_area :opis %>
  </div>
  <div class="field">
    <%= f.label :kraj %><br>
    <%= f.text_field :kraj %>
  </div>
  <div class="field">
    <%= f.label :zacetek %><br>
    <%= f.datetime_select :zacetek %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventis/edit.html.erb
<h1>Editing eventi</h1>

<%= render 'form' %>

<%= link_to 'Show', @eventi %> |
<%= link_to 'Back', eventis_path %>

app/views/eventis/index.html.erb
<h1>Listing eventis</h1>

<table>
  <thead>
    <tr>
      <th>Naslov</th>
      <th>Opis</th>
      <th>Kraj</th>
      <th>Zacetek</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @eventis.each do |eventi| %>
      <tr>
        <td><%= eventi.naslov %></td>
        <td><%= eventi.opis %></td>
        <td><%= eventi.kraj %></td>
        <td><%= eventi.zacetek.strftime('%I:%M %d %b, %Y') %></td>
        <td><%= link_to 'Show', eventi %></td>
        <td><%= link_to 'Edit', edit_eventi_path(eventi) %></td>
        <td><%= link_to 'Destroy', eventi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Eventi', new_eventi_path %>

app/views/eventis/new.html.erb
<h1>New eventi</h1>

<%= render 'form' %>

<%= link_to 'Back', eventis_path %>

app/views/eventis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Naslov:</strong>
  <%= @eventi.naslov %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @eventi.opis %>
</p>

<p>
  <strong>Kraj:</strong>
  <%= @eventi.kraj %>
</p>

<p>
  <strong>Zacetek:</strong>
  <%= @eventi.zacetek %>
</p>

<%= link_to 'Edit', edit_eventi_path(@eventi) %> |
<%= link_to 'Back', eventis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "SandiMVP spletna stran" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller.controller_name %>">
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/sl_SI/all.js#xfbml=1&appId=568462169877245";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
      <!-- Admin Panel -->
      
        <div class="admin panel-12 small-12" style="display:none">
          <%= link_to 'Dodaj Blog', @blog, class: "button", remote: true %>

        </div>
      
      <!-- End Admin Panel -->
      <!-- Header -->
        <header>
          <%= image_tag "header_logo.png", class: "logo" %>
          <%= image_tag "header_logo_y.png", class: "logo_yellow" %>
          <%= image_tag "header_logo2.png", class: "logo2" %>
          <nav>
            <ul>
              <li><%= link_to "Domov", domov_path, class: "button levo" %></li>
              <li><%= link_to "Bio", bio_path, class: "button levo" %></li>
              <li><%= link_to "Fotkiš", galerija_path, class: "button levo" %></li>
            </ul>
          </nav>
          <div id="login">
            <% if current_user %>
              Prijavljen kot <strong><%= current_user.name %></strong>
              <%= link_to "Odjava", signout_path, id: "sign_out" %>
            <% else %>
              <%= link_to "Prijava", "/auth/facebook", id: "sign_in" %>
            <% end %>
          </div>
        </header>
      <!-- End Header -->
 
      <!-- Content -->
      <div class="content">
        <%= yield %>
      </div>
      <!-- End Content -->
 
 
      <!-- Footer -->
      <footer>
        <div class="panel-12 small-12">
          <%= image_tag "footer_bg.png", class: 'footer_bg' %>
          <a href="http://www.spletko.eu/"><%= image_tag "footer_logo.png", class: 'spletko' %></a>
          <%= image_tag "powered-by-rails.png", class: 'rails' %>
      </div>
      </footer>
 
      <!-- End Footer -->
 
 

    
    <%= javascript_include_tag "application" %>



  </body>
</html>